version: '3.8'

services:
  nestapp: 
    image: lsharon1778/ecommerce-sharonesaa
    ports:
        - '3000:3000'
    env_file:
        - .env.development
    depends_on:
        - db
 
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env.development
    ports:
      - '5430:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
